rplidar_node:
  ros__parameters:
    channel_type: serial
    serial_port: /dev/rplidar
    serial_baudrate: 115200
    frame_id: laser_link #laser_frame
    inverted: false
    angle_compensate: true
    scan_mode: Sensitivity