teleop_twist_joy:
  ros__parameters:

    require_enable_button: true

    enable_button: 5         # RB
    enable_turbo_button: 4   # LB
    
    axis_linear.x: 1         # left stick vertical
    scale_linear.x: 0.6
    scale_linear_turbo.x: 1.2

    axis_angular.yaw: 3      # right stick horizontal
    scale_angular.yaw: 1.0
    scale_angular_turbo.yaw: 1.8

    axis_linear.y: -1
    axis_linear.z: -1
    axis_angular.roll: -1
    axis_angular.pitch: -1

    deadzone: 0.2
