controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    ackermann_controller:
      type: ackermann_steering_controller/AckermannSteeringController

joint_state_broadcaster:
  ros__parameters:
    publish_rate: 50.0

ackermann_controller:
  ros__parameters:
    
    # === TRACTION ===
    traction_joints_names:
      - left_rear_wheel_joint
      - right_rear_wheel_joint
    
    traction_joints_state_names:
      - left_rear_wheel_joint
      - right_rear_wheel_joint
    
    # === STEERING ===
    steering_joints_names:
      - left_steering_hinge_joint
      - right_steering_hinge_joint
    
    steering_joints_state_names:
      - left_steering_hinge_joint
      - right_steering_hinge_joint
    
    traction_wheels_radius: 0.033
    
    traction_track_width: 0.17
    
    steering_track_width: 0.11
    
    wheelbase: 0.2
    
    front_steering: true
    open_loop: false
    enable_odom_tf: true
    reference_timeout: 1.0
    use_stamped_vel: true
    
    base_frame_id: base_footprint
    odom_frame_id: odom
    
    update_rate: 100
    
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.0
        min_velocity: -0.5
        has_acceleration_limits: true
        max_acceleration: 0.8
        min_acceleration: -0.8
    
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 1.0
        min_velocity: -1.0
        has_acceleration_limits: true
        max_acceleration: 1.5
        min_acceleration: -1.5